# -*- coding: utf-8 -*-
"""Copy of Lab02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Q3aTym_5y1AL6zlaNBvlxgpSmjHE8CZ
"""

import numpy as np
import pandas as pd

"""1. Загрузка данных"""

df = pd.read_csv('/content/sample_data/house_price_regression_dataset.csv')

"""https://www.kaggle.com/datasets/prokshitha/home-value-insights"""

# 'Square_Footage': Размер дома в квадратных футах. Более крупные дома,
# как правило, стоят дороже.

# 'Num_Bedrooms': Количество спален в доме. Большее количество спален
# обычно увеличивает стоимость дома.

# 'Num_Bathrooms': Количество ванных комнат в доме. Дома с большим количеством
# ванных комнат, как правило, стоят дороже.

# 'Year_Built': Год постройки дома. Более старые дома могут стоить дешевле
# из-за износа.

# 'Lot_Size': Размер участка, на котором построен дом, измеряется в акрах.
# Большие участки, как правило, увеличивают стоимость недвижимости.

# 'Garage_Size': Количество автомобилей, которые могут поместиться в гараже.
# Дома с большими гаражами обычно стоят дороже.

# 'Neighborhood_Quality': Оценка качества района по шкале от 1 до 10, где
# 10 означает высокое качество района. В лучших районах обычно более высокие цены.

# 'House_Price' (целевая переменная): цена дома, которая является зависимой
# переменной, которую вы пытаетесь предсказать.

df

"""2. Предобработка данных"""

# Проверим есть ли столбы с пропущенными значениями
df.isna().any()

"""3. Загрузка модели, обучение

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

model = LinearRegression()

X = df.drop('House_Price', axis = 1)
X = scaler.fit_transform(X)

y = df[['House_Price']]
y = scaler.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Обучаем
model.fit(X_train, y_train)

# Делаем предсказание
y_pred = model.predict(X_test)

df1 = pd.DataFrame(y_pred)

df1

"""4. Оценка модели"""

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# MSE (Среднеквадратичная ошибка): чем ближе к 0, тем лучше
mse = mean_squared_error(y_test, y_pred)

# RMSE (Корень из MSE): ошибка в тех же единицах, что и целевая переменная
# (например, в рублях или метрах)
rmse = mean_squared_error(y_test, y_pred, squared=False)

# MAE (Средняя абсолютная ошибка): среднее отклонение
mae = mean_absolute_error(y_test, y_pred)

# R^2 (Коэффициент детерминации): точность от 0 до 1
r2 = r2_score(y_test, y_pred)

